### ISSUE TITLE
problems with rendering

### ISSUE THREAD

**Issue by klimanekt** [spacea/amuthesis-quarto#1]
While rendering the file a following message appears: 

updating tlmgr

updating existing packages
finding package for bera.sty

compilation failed- no matching packages
LaTeX Error: File `bera.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.27 \RequirePackage
                    {mathpazo}^^M 

How this could be solved?

**Comment by Nowosad** [comment]
Hi @klimanekt -- I was unable to reproduce your error, however, when I tried to run the template I got some other ones. Thus, I made some changes and now it runs locally on my computer. Can you also try the newest version?

**Comment by klimanekt** [comment]
Thank you a lot!! Now the template is rendering perfectly and the resulting pdf is as expected. Well done!
